// Name of the project
module backend

// This file is auto-generated by Go Modules. Do not edit manually.

// =====================================================================================================================================================================================================
// The go.mod file is the heart of a Go project (the Module). 
// It defines the module's path and manages the dependencies. 
// Initializing the Module
//		This file has been generated with "go init" command followed by the Module Path.
//		For a project intended for GitHub, the convention is to use the repository URL as the path. 
//			go mod init github.com/ckl67/skoreflow
//		This command initializing a new Go module in the current directory with the specified path.
//			module github.com/ckl67/skoreflow
//			go 1.24
//
//	However, for autonomy, I prefered no to publish it as a module, and use it a local name like "backend" in this case.		
//
//	Managing Dependencies
//	* go mod tidy 
//		is a command that helps maintain the go.mod file by adding any missing dependencies and removing any that are no longer needed.
//		It ensures that the go.mod file accurately reflects the dependencies used in your codebase.
//  * go get package 
//		is used to add a specific dependency to your project. 
//		It fetches the package and updates the go.mod file accordingly.
//  * go get package@none 
//		is used to remove a specific dependency from your project. 
//		It updates the go.mod file to reflect the removal of the package.
//  * go clean -modcache 
//		is used to clean the module cache, which is where Go stores downloaded modules. 
//		This can be useful if you want to free up disk space or if you encounter issues with corrupted modules in the cache.
// =====================================================================================================================================================================================================

// =====================================================================================================================================================================================================
// | Package                                  |   Role / Usage principal                                                                                                                                |
// | ---------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
// | `github.com/gin-contrib/cors`            |  Middleware pour **Golang Gin** permettant de gérer les **CORS** (Cross-Origin Resource Sharing) pour ton API.                                          |
// | `github.com/gin-gonic/gin`               |  Framework web léger et performant pour Go, utilisé pour créer des **routes, handlers, middlewares**, etc.                                              |
// | `github.com/glebarez/sqlite`             |  Driver **SQLite** compatible avec **GORM**, permettant d’utiliser SQLite comme base de données locale pour tests ou production légère.                 |
// | `github.com/go-playground/validator/v10` |  Librairie de **validation de structs** Go. Permet de valider des champs via des tags (`validate:"required,email"`) pour les formulaires, modèles, etc. |
// | `github.com/golang-jwt/jwt/v5`           |  Gestion des **JSON Web Tokens (JWT)** pour l’authentification et l’autorisation dans l’API.                                                            |
// | `github.com/golobby/config/v3`           |  Librairie pour **charger la configuration** depuis fichiers `.env` ou variables d’environnement avec mapping direct sur des structs Go.                |
// | `github.com/google/uuid`                 |  Génération d’**UUIDs** pour identifiants uniques, tokens, clés, etc.                                                                                   |
// | `github.com/mozillazg/go-unidecode`      |  **Translittération Unicode → ASCII**. Par exemple `Éléphant.pdf` devient `Elephant.pdf`. Utile pour noms de fichiers ou URLs “sûres”.                  |
// | `github.com/stretchr/testify`            |  Framework de **tests unitaires** Go, avec assertions (`assert`) et mocks pour simplifier l’écriture de tests.                                          |
// | `golang.org/x/crypto`                    |  Fournit des fonctions **cryptographiques avancées**, comme bcrypt, PBKDF2, AES, etc., pour le hachage des mots de passe et la sécurité.                |
// | `gorm.io/driver/mysql`                   |  Driver **MySQL/MariaDB** pour GORM. Permet de se connecter et interagir avec une base MySQL via GORM.                                                  |
// | `gorm.io/driver/postgres`                |  Driver **PostgreSQL** pour GORM. Permet de se connecter et interagir avec une base PostgreSQL via GORM.                                                |
// | `gorm.io/gorm`                           |  ORM (**Object-Relational Mapping**) pour Go. Facilite les interactions avec différentes bases SQL (MySQL, PostgreSQL, SQLite) avec des structs Go.     |
// =====================================================================================================================================================================================================

go 1.24.0

require (
	github.com/gin-contrib/cors v1.7.6
	github.com/gin-gonic/gin v1.11.0
	github.com/glebarez/sqlite v1.11.0
	github.com/go-playground/validator/v10 v10.30.1
	github.com/golang-jwt/jwt/v5 v5.3.1
	github.com/golobby/config/v3 v3.2.2
	github.com/mozillazg/go-unidecode v0.2.0
	golang.org/x/crypto v0.48.0
	gorm.io/driver/mysql v1.6.0
	gorm.io/driver/postgres v1.6.0
	gorm.io/gorm v1.31.1
)

require (
	filippo.io/edwards25519 v1.1.0 // indirect
	github.com/BurntSushi/toml v0.4.1 // indirect
	github.com/bytedance/sonic v1.14.0 // indirect
	github.com/bytedance/sonic/loader v0.3.0 // indirect
	github.com/cloudwego/base64x v0.1.6 // indirect
	github.com/dustin/go-humanize v1.0.1 // indirect
	github.com/gabriel-vasile/mimetype v1.4.12 // indirect
	github.com/gin-contrib/sse v1.1.0 // indirect
	github.com/glebarez/go-sqlite v1.21.2 // indirect
	github.com/go-playground/locales v0.14.1 // indirect
	github.com/go-playground/universal-translator v0.18.1 // indirect
	github.com/go-sql-driver/mysql v1.8.1 // indirect
	github.com/goccy/go-json v0.10.5 // indirect
	github.com/goccy/go-yaml v1.18.0 // indirect
	github.com/golobby/cast v1.1.4 // indirect
	github.com/golobby/dotenv v1.2.0 // indirect
	github.com/golobby/env/v2 v2.1.0 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761 // indirect
	github.com/jackc/pgx/v5 v5.6.0 // indirect
	github.com/jackc/puddle/v2 v2.2.2 // indirect
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.5 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/klauspost/cpuid/v2 v2.3.0 // indirect
	github.com/kr/text v0.2.0 // indirect
	github.com/leodido/go-urn v1.4.0 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/ncruces/go-strftime v1.0.0 // indirect
	github.com/pelletier/go-toml/v2 v2.2.4 // indirect
	github.com/quic-go/qpack v0.5.1 // indirect
	github.com/quic-go/quic-go v0.54.0 // indirect
	github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec // indirect
	github.com/rogpeppe/go-internal v1.14.1 // indirect
	github.com/twitchyliquid64/golang-asm v0.15.1 // indirect
	github.com/ugorji/go/codec v1.3.0 // indirect
	go.uber.org/mock v0.5.0 // indirect
	golang.org/x/arch v0.20.0 // indirect
	golang.org/x/exp v0.0.0-20251023183803-a4bb9ffd2546 // indirect
	golang.org/x/mod v0.32.0 // indirect
	golang.org/x/net v0.49.0 // indirect
	golang.org/x/sync v0.19.0 // indirect
	golang.org/x/sys v0.41.0 // indirect
	golang.org/x/text v0.34.0 // indirect
	golang.org/x/tools v0.41.0 // indirect
	google.golang.org/protobuf v1.36.9 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	modernc.org/libc v1.67.6 // indirect
	modernc.org/mathutil v1.7.1 // indirect
	modernc.org/memory v1.11.0 // indirect
	modernc.org/sqlite v1.45.0 // indirect
)
